baseURL = "https://jcrd.github.io/hugo-theme-readme"
languageCode = "en-US"
title = "Website name"

theme = "hugo-theme-readme"
# allow building `exampleSite` within theme dir
themesDir = "../.."

enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

enableGitInfo = true

# allow HTML in markdown
[markup.goldmark.renderer]
unsafe = true

# required by PurgeCSS
[build]
writeStats = true

[author]
name = "Your name"

[params]
commitURL = "https://github.com/jcrd/hugo-theme-readme/commit"
description = "Your site description"
highlight = true
projectsPhrase = "technologies"
vanityFooter = false
supportURL = "https://ko-fi.com/twiddlingbits"

# [params.logo]
# file = "images/icon.png"
# width = 32
# height = 32
# title = true

# [params.analytics]
# goatcounter = ""

[[menu.main]]
identifier = "about"
name = "about"
url = "/about"
weight = 1
[menu.main.params]
icon = true

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 2
[menu.main.params]
icon = true

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 3
[menu.main.params]
icon = true

[permalinks]
posts = "/:title/"
