baseURL = "https://example.com"
languageCode = "en-US"
title = "Website name"

theme = "readme"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

# required by PurgeCSS
[build]
writeStats = true

[params]
description = "Your site description"
author = "Your name"
highlight = true

# [params.analytics]
# goatcounter = ""

[[menu.main]]
identifier = "about"
name = "about"
url = "/about"
weight = 1

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 3

[permalinks]
posts = "/:title/"
